/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package Boundary_Package;

import Control_Package.LoginControl;
import Control_Package.RegisterControl;
import DAOS.exceptions.NonexistentEntityException;
import Entities.Views.ViewCargo;
import Entities.Views.ViewPersona;
import java.awt.event.KeyEvent;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JFormattedTextField;
import javax.swing.JOptionPane;
import utilities.helpers.RegexFormatter;
import utilities.helpers.RegularExpression;

/**
 *
 * @author dastg_000
 */
public class DeletePersonGui extends javax.swing.JPanel {

    RegisterControl registerControl = new RegisterControl();
    ViewPersona person = null;
    public DefaultComboBoxModel boxModel = new DefaultComboBoxModel();

    public DeletePersonGui() {
        initComponents();
        ComboBoxFill();
        Integrity();
        DataPanel.setVisible(false);
        ModifyPanel.setVisible(false);
        nombreTF.setEditable(false);
        apellidoTF.setEditable(false);
        telefonoTF.setEditable(false);
        cargoTF.setEditable(false);

    }

    /**
     * This method is called from within the constructor to initialize the form. WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane1 = new javax.swing.JTabbedPane();
        DeletePerson = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        DataPanel = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        eliminarBT = new javax.swing.JButton();
        nombreTF = new javax.swing.JFormattedTextField();
        apellidoTF = new javax.swing.JFormattedTextField();
        cargoTF = new javax.swing.JFormattedTextField();
        telefonoTF = new javax.swing.JFormattedTextField();
        CedulaTF = new javax.swing.JFormattedTextField();
        ModifyPerson = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        jSeparator2 = new javax.swing.JSeparator();
        ModifyPanel = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        MListRol = new javax.swing.JComboBox();
        MActualizarBT = new javax.swing.JButton();
        MnombreTF = new javax.swing.JFormattedTextField();
        MapellidoTF = new javax.swing.JFormattedTextField();
        MtelTF = new javax.swing.JFormattedTextField();
        MdireccionTF = new javax.swing.JFormattedTextField();
        McorreoTF = new javax.swing.JFormattedTextField();
        McedulaTF = new javax.swing.JFormattedTextField();

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel1.setText("CEDULA");

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel2.setText("Nombre");

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel3.setText("Apellido");

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel4.setText("Cargo");

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel5.setText("Telefono");

        eliminarBT.setFont(new java.awt.Font("Ebrima", 1, 14)); // NOI18N
        eliminarBT.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/cross.png"))); // NOI18N
        eliminarBT.setText("ELIMINAR");
        eliminarBT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                eliminarBTActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout DataPanelLayout = new javax.swing.GroupLayout(DataPanel);
        DataPanel.setLayout(DataPanelLayout);
        DataPanelLayout.setHorizontalGroup(
            DataPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(DataPanelLayout.createSequentialGroup()
                .addGroup(DataPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3)
                    .addComponent(jLabel4)
                    .addComponent(jLabel2)
                    .addComponent(jLabel5))
                .addGap(18, 18, 18)
                .addGroup(DataPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(nombreTF)
                    .addComponent(apellidoTF)
                    .addComponent(cargoTF)
                    .addComponent(telefonoTF, javax.swing.GroupLayout.DEFAULT_SIZE, 426, Short.MAX_VALUE))
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(DataPanelLayout.createSequentialGroup()
                .addGap(201, 201, 201)
                .addComponent(eliminarBT)
                .addContainerGap(157, Short.MAX_VALUE))
        );
        DataPanelLayout.setVerticalGroup(
            DataPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(DataPanelLayout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addGroup(DataPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(nombreTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(DataPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(apellidoTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(DataPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(cargoTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(21, 21, 21)
                .addGroup(DataPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(telefonoTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(49, 49, 49)
                .addComponent(eliminarBT)
                .addContainerGap(38, Short.MAX_VALUE))
        );

        CedulaTF.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                CedulaTFFocusLost(evt);
            }
        });
        CedulaTF.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                CedulaTFKeyPressed(evt);
            }
        });

        javax.swing.GroupLayout DeletePersonLayout = new javax.swing.GroupLayout(DeletePerson);
        DeletePerson.setLayout(DeletePersonLayout);
        DeletePersonLayout.setHorizontalGroup(
            DeletePersonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, DeletePersonLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(DeletePersonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(DataPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jSeparator1, javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, DeletePersonLayout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(CedulaTF)))
                .addContainerGap())
        );
        DeletePersonLayout.setVerticalGroup(
            DeletePersonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(DeletePersonLayout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(DeletePersonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(CedulaTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(DataPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        jTabbedPane1.addTab("Eliminar", DeletePerson);

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel6.setText("CEDULA");

        jLabel7.setText("Nombre");

        jLabel8.setText("Apellido");

        jLabel9.setText("Telefono");

        jLabel10.setText("Direccion");

        jLabel11.setText("Correo");

        jLabel12.setText("Rol");

        MListRol.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        MActualizarBT.setFont(new java.awt.Font("Gungsuh", 1, 14)); // NOI18N
        MActualizarBT.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/login.png"))); // NOI18N
        MActualizarBT.setText("Actualizar");
        MActualizarBT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MActualizarBTActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout ModifyPanelLayout = new javax.swing.GroupLayout(ModifyPanel);
        ModifyPanel.setLayout(ModifyPanelLayout);
        ModifyPanelLayout.setHorizontalGroup(
            ModifyPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ModifyPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(ModifyPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel12)
                    .addComponent(jLabel7)
                    .addComponent(jLabel8)
                    .addComponent(jLabel9)
                    .addComponent(jLabel10)
                    .addComponent(jLabel11))
                .addGap(18, 18, 18)
                .addGroup(ModifyPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(ModifyPanelLayout.createSequentialGroup()
                        .addComponent(MListRol, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 88, Short.MAX_VALUE)
                        .addComponent(MActualizarBT))
                    .addComponent(MnombreTF)
                    .addComponent(MapellidoTF)
                    .addComponent(MtelTF)
                    .addComponent(MdireccionTF)
                    .addComponent(McorreoTF))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        ModifyPanelLayout.setVerticalGroup(
            ModifyPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ModifyPanelLayout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addGroup(ModifyPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(MnombreTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(ModifyPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(MapellidoTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(ModifyPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(MtelTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(ModifyPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(MdireccionTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(ModifyPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11)
                    .addComponent(McorreoTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(ModifyPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(ModifyPanelLayout.createSequentialGroup()
                        .addGroup(ModifyPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel12)
                            .addComponent(MListRol, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 42, Short.MAX_VALUE))
                    .addComponent(MActualizarBT, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                .addContainerGap())
        );

        McedulaTF.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                McedulaTFFocusLost(evt);
            }
        });
        McedulaTF.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                McedulaTFKeyPressed(evt);
            }
        });

        javax.swing.GroupLayout ModifyPersonLayout = new javax.swing.GroupLayout(ModifyPerson);
        ModifyPerson.setLayout(ModifyPersonLayout);
        ModifyPersonLayout.setHorizontalGroup(
            ModifyPersonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ModifyPersonLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(ModifyPersonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jSeparator2)
                    .addGroup(ModifyPersonLayout.createSequentialGroup()
                        .addComponent(jLabel6)
                        .addGap(18, 18, 18)
                        .addComponent(McedulaTF, javax.swing.GroupLayout.PREFERRED_SIZE, 396, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 28, Short.MAX_VALUE))
                    .addComponent(ModifyPanel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        ModifyPersonLayout.setVerticalGroup(
            ModifyPersonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ModifyPersonLayout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addGroup(ModifyPersonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(McedulaTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(ModifyPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        jTabbedPane1.addTab("Modificar", ModifyPerson);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 524, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(47, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(41, 41, 41)
                .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 407, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(41, Short.MAX_VALUE))
        );

        jTabbedPane1.getAccessibleContext().setAccessibleName("Eliminar");
    }// </editor-fold>//GEN-END:initComponents

    private void eliminarBTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_eliminarBTActionPerformed
        try {
            registerControl.DeletePerson(person);
        } catch (NonexistentEntityException ex) {
            JOptionPane.showMessageDialog(null, "Error al eliminar el usuario", "ERROR", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_eliminarBTActionPerformed

    private void MActualizarBTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MActualizarBTActionPerformed
        //TODA LA LOGICA DE ACTUALIZAR
        ViewPersona p = new ViewPersona();
        p.setIdPersona(person.getIdPersona());
        p.setApellidoPersona(MapellidoTF.getText());
        p.setDireccionPersona(MdireccionTF.getText());
        p.setIdCargo(registerControl.traerCargo((String) MListRol.getSelectedItem()));
        p.setIdDrogueria(1);
        p.setMailPersona(McorreoTF.getText());
        p.setNombrePersona(MnombreTF.getText());
        p.setTelefonoPersona(Integer.valueOf(MtelTF.getText()));
        p.setNombrePersona(person.getNombreDeUsuario());
        p.setPassword(person.getPassword());
        p.setNombreDeUsuario(person.getNombreDeUsuario());
        try {
            if (registerControl.UpdatePerson(p)) {
                JOptionPane.showMessageDialog(null, "Cambios Realizados", "EXITO", JOptionPane.INFORMATION_MESSAGE);
            } else {
                JOptionPane.showMessageDialog(null, "Error al actualizar los datos", "ERROR", JOptionPane.ERROR_MESSAGE);
            }
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(null, "Error al actualizar los datos", "ERROR", JOptionPane.ERROR_MESSAGE);
        }


    }//GEN-LAST:event_MActualizarBTActionPerformed

    private void CedulaTFFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_CedulaTFFocusLost
    }//GEN-LAST:event_CedulaTFFocusLost

    private void McedulaTFFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_McedulaTFFocusLost
    }//GEN-LAST:event_McedulaTFFocusLost

    private void CedulaTFKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_CedulaTFKeyPressed
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            if (!this.CedulaTF.getText().isEmpty()) {
                person = registerControl.searchById(Integer.parseInt(this.CedulaTF.getText()));

                if (person != null) {
                    DataPanel.setVisible(true);
                    String nombre = person.getNombrePersona();
                    String apellido = person.getApellidoPersona();
                    int tel = person.getTelefonoPersona();
                    int cargo = person.getIdCargo();
                    this.nombreTF.setText(nombre);
                    this.apellidoTF.setText(apellido);
                    this.telefonoTF.setText(Integer.toString(tel));
                    this.cargoTF.setText(Integer.toString(cargo));



                } else {
                    JOptionPane.showMessageDialog(null, "Cedula invalida", "Mensaje", JOptionPane.ERROR_MESSAGE);
                }
            }
        }
    }//GEN-LAST:event_CedulaTFKeyPressed

    private void McedulaTFKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_McedulaTFKeyPressed
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            if (!this.McedulaTF.getText().isEmpty()) {
                person = registerControl.searchById(Integer.parseInt(this.McedulaTF.getText()));

                if (person != null) {
                    ModifyPanel.setVisible(true);
                    String nombre = person.getNombrePersona();
                    String apellido = person.getApellidoPersona();
                    String correo = person.getMailPersona();
                    String dir = person.getDireccionPersona();
                    int tel = person.getTelefonoPersona();
                    int cargo = person.getIdCargo();

                    this.MnombreTF.setText(nombre);
                    this.MapellidoTF.setText(apellido);
                    this.MtelTF.setText(Integer.toString(tel));
                    this.MdireccionTF.setText(dir);
                    this.McorreoTF.setText(correo);
                    this.MListRol.setSelectedIndex(cargo);

                } else {
                    JOptionPane.showMessageDialog(null, "Cedula invalida", "Mensaje", JOptionPane.ERROR_MESSAGE);
                }

            }
        }
    }//GEN-LAST:event_McedulaTFKeyPressed

    public void ComboBoxFill() {
        boxModel.addElement("Seleccione");
        for (ViewCargo car : registerControl.ListaCargos()) {
            this.boxModel.addElement(car.getTipoCargo());
        }
        MListRol.setModel(boxModel);
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JFormattedTextField CedulaTF;
    private javax.swing.JPanel DataPanel;
    private javax.swing.JPanel DeletePerson;
    private javax.swing.JButton MActualizarBT;
    private javax.swing.JComboBox MListRol;
    private javax.swing.JFormattedTextField MapellidoTF;
    private javax.swing.JFormattedTextField McedulaTF;
    private javax.swing.JFormattedTextField McorreoTF;
    private javax.swing.JFormattedTextField MdireccionTF;
    private javax.swing.JFormattedTextField MnombreTF;
    private javax.swing.JPanel ModifyPanel;
    private javax.swing.JPanel ModifyPerson;
    private javax.swing.JFormattedTextField MtelTF;
    private javax.swing.JFormattedTextField apellidoTF;
    private javax.swing.JFormattedTextField cargoTF;
    private javax.swing.JButton eliminarBT;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JFormattedTextField nombreTF;
    private javax.swing.JFormattedTextField telefonoTF;
    // End of variables declaration//GEN-END:variables

    private void Integrity() {
        new RegexFormatter(RegularExpression.NATURAL_NUMBERS).install(McedulaTF);
        new RegexFormatter(RegularExpression.NATURAL_NUMBERS).install(CedulaTF);
        new RegexFormatter(RegularExpression.WORDS).install(MnombreTF);
        new RegexFormatter(RegularExpression.WORDS).install(MapellidoTF);
        new RegexFormatter(RegularExpression.NATURAL_NUMBERS).install(MtelTF);
        new RegexFormatter(RegularExpression.EMAIL).install(McorreoTF);
    }
}
