INSERT INTO lrlineroa.CARGO (ID_CARGO, TIPO_CARGO) 
	VALUES (1, 'Administrador')
INSERT INTO lrlineroa.CARGO (ID_CARGO, TIPO_CARGO) 
	VALUES (2, 'Vendedor')

INSERT INTO lrlineroa.DROGUERIA (ID_DROGUERIA, NOMBRE_DROGUERIA, TELEFONO_DROGUERIA, DIRECCION_DROGUERIA) 
	VALUES (1, 'Drogueria Nuevo MIlenio', '5555555', 'calle falsa 123')
	
INSERT INTO lrlineroa.PERSONA (ID_PERSONA, ID_CARGO, ID_DROGUERIA, NOMBRE_PERSONA, APELLIDO_PERSONA, TELEFONO_PERSONA, DIRECCION_PERSONA, PASSWORD, NOMBRE_DE_USUARIO)
	VALUES (1055555555, 1, 1, 'Leonardo', 'Linero', 5555555, 'avenida siempre viva 2445', 's02258001', 'lrlineroa')
	
INSERT INTO lrlineroa.PERSONA (ID_PERSONA, ID_CARGO, ID_DROGUERIA, NOMBRE_PERSONA, APELLIDO_PERSONA, TELEFONO_PERSONA, DIRECCION_PERSONA, PASSWORD, NOMBRE_DE_USUARIO)
	VALUES (1032333333, 1, 1, 'Edward', 'Rojas', 3333333, '345 oasis st', 's02258009', 'earojasc')
	
INSERT INTO lrlineroa.PERSONA (ID_PERSONA, ID_CARGO, ID_DROGUERIA, NOMBRE_PERSONA, APELLIDO_PERSONA, TELEFONO_PERSONA, DIRECCION_PERSONA, PASSWORD, NOMBRE_DE_USUARIO)
	VALUES (1032333444, 2, 1, 'Stiven', 'Gonzalez', 3333333, 'cra 123', 's02257765', 'dsgonzalezh')
		
INSERT INTO lrlineroa.PERSONA (ID_PERSONA, ID_CARGO, ID_DROGUERIA, NOMBRE_PERSONA, APELLIDO_PERSONA, TELEFONO_PERSONA, DIRECCION_PERSONA, PASSWORD, NOMBRE_DE_USUARIO)
	VALUES (1050500500, 2, 1, 'Mauricio', 'Herrera', 1111111, 'cll 9 # 98', 's02257771', 'maherrerapu')
	
INSERT INTO lrlineroa.PERSONA (ID_PERSONA, ID_CARGO, ID_DROGUERIA, NOMBRE_PERSONA, APELLIDO_PERSONA, TELEFONO_PERSONA, DIRECCION_PERSONA, PASSWORD, NOMBRE_DE_USUARIO)
	VALUES (1060600600, 2, 1, 'Jesid', 'Mejia', 2222222, 'tr 32 # 90', 's02258258', 'jemmejiaca')
	
INSERT INTO lrlineroa.PERSONA (ID_PERSONA, ID_CARGO, ID_DROGUERIA, NOMBRE_PERSONA, APELLIDO_PERSONA, TELEFONO_PERSONA, DIRECCION_PERSONA, PASSWORD, NOMBRE_DE_USUARIO)
	VALUES (1070700700, 2, 1, 'Camilo', 'Peña', 8888888, '345 oasis st', 's02257956', 'capenap')