GRANT DELETE,INSERT,SELECT,UPDATE ON VIEW_BITACORA TO earojasc, dsgonzalezh, maherrerapu, jemmejiaca, capenap
GRANT DELETE,INSERT,SELECT,UPDATE ON VIEW_CARGO TO earojasc, dsgonzalezh, maherrerapu, jemmejiaca, capenap
GRANT DELETE,INSERT,SELECT,UPDATE ON VIEW_DROGUERIA TO earojasc, dsgonzalezh, maherrerapu, jemmejiaca, capenap
GRANT DELETE,INSERT,SELECT,UPDATE ON VIEW_FABRICANTE TO earojasc, dsgonzalezh, maherrerapu, jemmejiaca, capenap
GRANT DELETE,INSERT,SELECT,UPDATE ON VIEW_FACTURA TO earojasc, dsgonzalezh, maherrerapu, jemmejiaca, capenap
GRANT DELETE,INSERT,SELECT,UPDATE ON VIEW_INVENTARIORPT TO earojasc, dsgonzalezh, maherrerapu, jemmejiaca, capenap
GRANT DELETE,INSERT,SELECT,UPDATE ON VIEW_MEDICAMENTO TO earojasc, dsgonzalezh, maherrerapu, jemmejiaca, capenap
GRANT DELETE,INSERT,SELECT,UPDATE ON VIEW_PEDIDO TO earojasc, dsgonzalezh, maherrerapu, jemmejiaca, capenap
GRANT DELETE,INSERT,SELECT,UPDATE ON VIEW_PERSONA TO earojasc, dsgonzalezh, maherrerapu, jemmejiaca, capenap
GRANT DELETE,INSERT,SELECT,UPDATE ON VIEW_PRESENTACION TO earojasc, dsgonzalezh, maherrerapu, jemmejiaca, capenap
GRANT DELETE,INSERT,SELECT,UPDATE ON VIEW_PROVEEDOR TO earojasc, dsgonzalezh, maherrerapu, jemmejiaca, capenap
GRANT DELETE,INSERT,SELECT,UPDATE ON VIEW_TIPO_PRODUCTO TO earojasc, dsgonzalezh, maherrerapu, jemmejiaca, capenap
GRANT DELETE,INSERT,SELECT,UPDATE ON VIEW_USO_MEDIC TO earojasc, dsgonzalezh, maherrerapu, jemmejiaca, capenap
GRANT DELETE,INSERT,SELECT,UPDATE ON BITACORA TO earojasc, dsgonzalezh, maherrerapu, jemmejiaca, capenap
GRANT DELETE,INSERT,SELECT,UPDATE ON CARGO TO earojasc, dsgonzalezh, maherrerapu, jemmejiaca, capenap
GRANT DELETE,INSERT,SELECT,UPDATE ON DROGUERIA TO earojasc, dsgonzalezh, maherrerapu, jemmejiaca, capenap
GRANT DELETE,INSERT,SELECT,UPDATE ON FABRICANTE TO earojasc, dsgonzalezh, maherrerapu, jemmejiaca, capenap
GRANT DELETE,INSERT,SELECT,UPDATE ON FACTURA TO earojasc, dsgonzalezh, maherrerapu, jemmejiaca, capenap
GRANT DELETE,INSERT,SELECT,UPDATE ON INVENTARIO_RPT TO earojasc, dsgonzalezh, maherrerapu, jemmejiaca, capenap
GRANT DELETE,INSERT,SELECT,UPDATE ON MEDICAMENTO TO earojasc, dsgonzalezh, maherrerapu, jemmejiaca, capenap
GRANT DELETE,INSERT,SELECT,UPDATE ON PEDIDO TO earojasc, dsgonzalezh, maherrerapu, jemmejiaca, capenap
GRANT DELETE,INSERT,SELECT,UPDATE ON PERSONA TO earojasc, dsgonzalezh, maherrerapu, jemmejiaca, capenap
GRANT DELETE,INSERT,SELECT,UPDATE ON PRESENTACION TO earojasc, dsgonzalezh, maherrerapu, jemmejiaca, capenap
GRANT DELETE,INSERT,SELECT,UPDATE ON PROVEEDOR TO earojasc, dsgonzalezh, maherrerapu, jemmejiaca, capenap
GRANT DELETE,INSERT,SELECT,UPDATE ON TIPO_PRODUCTO TO earojasc, dsgonzalezh, maherrerapu, jemmejiaca, capenap
GRANT DELETE,INSERT,SELECT,UPDATE ON USO_MEDICAMENTO TO earojasc, dsgonzalezh, maherrerapu, jemmejiaca, capenap
